[package]
name = "url_shortner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
hex = "0.4.3"
ring = "0.17.0"
url_open = "0.0.2"
